flask-api:
  restart: always
  build: ./flask-api
  expose:
    - "80"
  links:
    - mongo:mongo
  volumes:
    - /flask-api/
  env_file: .env
  command: /usr/local/bin/uwsgi --ini /flask-api/uwsgi.ini

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
  - /usr/local/bin/uwsgi
  volumes_from:
    - flask-api
  links:
    - flask-api:flask-api

data:
  image: mongo:latest
  volumes:
    - /var/lib/mongo
  command: "true"

mongo:
  restart: always
  image: mongo:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
