flask-api:
  restart: on-failure:10
  build: ./flask-api
  expose:
    - "8000"
#  links:
#    - mongo:mongo
  env_file: .env
  command: uwsgi --ini /flask-api/uwsgi.ini
  volumes:
    - /flask-api
    - /usr/src/app
    - /var/log/uwsgi
  container_name: flask-api

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
  - flask-api
  container_name: nginx

#data:
#  image: mongo:latest
#  volumes:
#    - /var/lib/mongo
#  command: "true"
#  container_name: mongo-data
#
#mongo:
#  restart: always
#  image: mongo:latest
#  volumes_from:
#    - data
#  ports:
#    - "5432:5432"
#  container_name: mongo
